apiVersion: v2
name: grafana
version: 6.4.4
appVersion: 7.4.1
kubeVersion: '^1.8.0-0'
description: Cloudx wrapper for grafana helm chart
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/mmerrill3/argocd-applications
maintainers:
  - name: mmerrill3
    email: jjpaacks@gmail.com
engine: gotpl
type: application
dependencies:
- name: grafana
  version: "7.4.1"
  repository: https://grafana.github.io/helm-charts
