apiVersion: v1
kind: Secret
metadata:
  name: grafana-password
  namespace: {{ template "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
